### ISSUE TITLE
A2 Upgrade wait for completion

### ISSUE THREAD

**Issue by chrisg-fastlane** [mattray/managed-automate2-cookbook#8]
The Chef Automate services need at least four minutes to stabilise after an UPGRADE cookbook run.  Perhaps wait until it reports all services restarted and running again.

**Comment by mattray** [comment]
With 0.10.0 it's more resilient to multiple runs of the same cookbook over and over, noticing that the upgrade is already happening. But if you have additional tests or services after the upgrade is kicked off Automate may not be ready yet. I'm going to close this for now but if it needs to be revisited we could put a while loop or something on the "chef-automate upgrade status" to wait for the completion if necessary
